# Generated by Django 5.2.4 on 2025-07-09 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Palavra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letras_certas", models.CharField(blank=True, max_length=100)),
                ("letras_erradas", models.CharField(blank=True, max_length=100)),
                ("jogador", models.CharField(max_length=100)),
                ("finalizada", models.BooleanField(default=False)),
                ("venceu", models.BooleanField(default=False)),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "palavra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jogo.palavra"
                    ),
                ),
            ],
        ),
    ]
